name: dash
recipe: drupal8
config:
  webroot: web
services:
#  appserver:
#    run:
#      - bash config/init.sh
#    overrides:
#      environment:
#        MINK_DRIVER_ARGS: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
#        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
#        MINK_DRIVER_CLASS: 'Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver'
#        BROWSERTEST_OUTPUT_DIRECTORY: '/app/web/sites/default/files/phpunit'
#        SIMPLETEST_DB: 'mysql://drupal8:drupal8@database/drupal8'
#        SIMPLETEST_BASE_URL: 'https://address-sandbox.lndo.site/'
#        PHP_IDE_CONFIG: "serverName=appserver"
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  node:
    type: node:12
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit --debug --configuration /app/web/core/phpunit.xml
  phpcs:
    service: appserver
    description: |-
      Check Drupal coding standards

      Example:
        lando phpcs path/to/drupal/example_module
  phpcbf:
    service: appserver
    description: |-
      Automatically fix coding standards

      Example:
        lando phpcbf path/to/drupal/example_module
  xdebug-on:
    user: root
    service: appserver
    description: Enable Xdebug.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
  xdebug-off:
    user: root
    service: appserver
    description: |-
      Disable Xdebug.
      (Recommended for performance when not actively debugging)
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
  drupalorg:
    service: appserver
    description: A command line tool for interfacing with Drupal.org.
  npm:
    service: node
    description: |
      Run NPM commands. Be sure to be inside your target theme directory.
      cd path/to/theme
      lando npm install
