name: dash
recipe: drupal9
config:
  webroot: web
  php: 7.4
services:
  appserver:
    overrides:
      environment:
        SIMPLETEST_BASE_URL: "https://appserver"
        SIMPLETEST_DB: "sqlite://localhost/tmp/db.sqlite"
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://chrome:9515"]'
        DRUSH_OPTIONS_ROOT: '/app/web'
        DRUSH_OPTIONS_URI: 'http://dash.lndo.site'
  chrome:
    type: compose
    app_mount: false
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --verbose --whitelisted-ips=
  node:
    type: node:12
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit"
    cmd: /app/vendor/bin/phpunit --configuration /app/web/core/phpunit.xml.dist
  phpcs:
    service: appserver
    description: |-
      Check Drupal coding standards

      Example:
        lando phpcs path/to/drupal/example_module
  phpcbf:
    service: appserver
    description: |-
      Automatically fix coding standards

      Example:
        lando phpcbf path/to/drupal/example_module
  xdebug-on:
    user: root
    service: appserver
    description: Enable Xdebug.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
  xdebug-off:
    user: root
    service: appserver
    description: |-
      Disable Xdebug.
      (Recommended for performance when not actively debugging)
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
  drupalorg:
    service: appserver
    description: A command line tool for interfacing with Drupal.org.
  npm:
    service: node
    description: |
      Run NPM commands. Be sure to be inside your target theme directory.
      cd path/to/theme
      lando npm install
